os: linux
dist: xenial
language: node_js
node_js: 16
install:
  - sudo apt update
  - sudo apt install python3-pip
  - pip3 install -r requirements.txt
script:
  - yarn build
  - python3 deployCloudFormation.py
